# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('idfeedback', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'feedback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('iditem', models.AutoField(primary_key=True, serialize=False)),
                ('itemname', models.CharField(db_column='itemName', max_length=45)),
                ('itemstatus', models.CharField(db_column='itemStatus', max_length=10)),
                ('itemnote', models.CharField(blank=True, db_column='itemNote', max_length=100, null=True)),
                ('itemmodtime', models.DateTimeField(db_column='itemModTime')),
            ],
            options={
                'db_table': 'item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('idposition', models.AutoField(primary_key=True, serialize=False)),
                ('container', models.CharField(max_length=45)),
                ('block', models.CharField(max_length=45)),
                ('pstnnote', models.CharField(blank=True, db_column='pstnNote', max_length=100, null=True)),
            ],
            options={
                'db_table': 'position',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('idroom', models.AutoField(primary_key=True, serialize=False)),
                ('roomname', models.CharField(db_column='roomName', max_length=10, unique=True)),
            ],
            options={
                'db_table': 'room',
                'managed': False,
            },
        ),
    ]
